### ISSUE TITLE
 Sivupalkin sijainti epäselvänä?

### ISSUE THREAD

**Issue by hamidaebadi** [tiina0/taitotalo-group-project#1]
## Sivupalkki vasempaan reunaan kiinnitettynä vai irrallaan reunasta ? ##

En muista, pääsimmekö **sivupalkin sijainnista** yhteiseen ymmärrykseen vai ei. Muistaakseni puhuttiin siitä jotain, mutta minulla se jäi epäselvänä.

Eli meillä on kaksi vaihtoehtoa:
* Irrallaan reunasta
* Kiinnitettynä vasempaan reunaan

Voisitteko te kertoa omaa mielipidettä?  Sitten, kun on päästy yhteisymmärrykseen, niin suljen tämän issuesin 😄

**Comment by tiina0** [comment]
Mun mielestä se voisi olla (samoin kun yläreunan navigaatiopalkki) **irrallaan** reunasta.

**Comment by hamidaebadi** [comment]
Noniiii, multa puuttui viime kerta mun pääsivun graafinen ilme. Nyt se on valmis kahdessa versiossa. Laitan tänne kuvat hahmottamista varten.
tässä kuvassa sivupalkki on kiinni vasemmasta reunasta.
<img width="896" alt="Screenshot 2021-03-24 at 21 12 22" src="https://user-images.githubusercontent.com/65080068/112371357-2faaf880-8ce7-11eb-8bda-0b50641f0320.png">


mut tässä kuvassa ei

<img width="904" alt="Screenshot 2021-03-24 at 21 18 10" src="https://user-images.githubusercontent.com/65080068/112371465-4fdab780-8ce7-11eb-84a4-b02d4b9ebe65.png">

**Comment by indrohoffmann** [comment]
Hamidin näytteiden perusteella soveltuu tumma ja reunassa kiinni oleva sivupalkki mun silmiin paremmin.

**Comment by tiina0** [comment]
Enemmän näkee mun mielestä sitä että sivupalkki on irrallaan ja lähempänä fiidiä (esimerkkejä: LinkedIn, Reddit ja muistaakseni Facebook). Jos palkki on ihan kiinni vasemmassa reunassa niin keskitetty fiidi saattaa näyttää oudolta etenkin isoilla näytöillä. Näkisin, että jos halutaan että palkki on kiinni reunassa niin sisältö pitäisi olla asemoitu sivulle niin ettei palkin ja sisällön väliin jäisi kauheasti tilaa.

**Comment by hamidaebadi** [comment]
@katjatikkanen ajatukset vielä kertomatta!
mutta hey, minäkin luulen, että sivupalkki irrallaan on hyvä idea. Mutta mitä mieltä ootte tästä rakenteesta nyt?
Jos sivupalkki irrallaan, navigaatiopalkki kiinnitetty, niin sitten taustaväri vähän harmaana ja muu sisältö on upotettu valkoiseen containeriin. 

@tiina0 @indrohoffmann @katjatikkanen 
<img width="938" alt="Screenshot 2021-03-25 at 9 52 22" src="https://user-images.githubusercontent.com/65080068/112438168-59e4d080-8d50-11eb-9d00-9d61d4e615e1.png">

**Comment by hamidaebadi** [comment]
**Suljen tämän keskustelun**
Päästiin yhteisymmärrykseen pääsivun rakenteesta ja väristä.
- Sivupalkki irrallaan lähellä feediä
